Completed command-line-basics exercise
BlakexLim/c0124-code-solutions pull request #57
Opened 2024-02-28 19:36 UTC by BlakexLim

![cmd line basics](https://github.com/BlakexLim/c0124-code-solutions/assets/132517914/e40226ac-03b3-4580-b98f-d9e9dcec7290)

2024-02-28 22:47 UTC, shawnkost requested changes
Need to answer the quiz questions

2024-02-28 22:47 UTC, shawnkost commented on command-line-basics/command-line-basics-quiz-notes.md
> +- What are the three virtues of a great programmer?
Don't forget about the quiz questions!

2024-02-28 23:03 UTC, BlakexLim commented on command-line-basics/command-line-basics-quiz-notes.md
> +- What are the three virtues of a great programmer?
noooo they didn't save

2024-03-18 14:59 UTC, shawnkost approved these changes
👍🏻

2024-03-18 19:30 UTC, merged